gxt -g III -i "III PC/american.txt" -o "III PC/american.gxt"
gxt -g III -i "III PC/english.txt" -o "III PC/english.gxt"
gxt -g III -i "III PC/french.txt" -o "III PC/french.gxt"
gxt -g III -i "III PC/german.txt" -o "III PC/german.gxt"
gxt -g III -i "III PC/italian.txt" -o "III PC/italian.gxt"
gxt -g III -i "III PC/spanish.txt" -o "III PC/spanish.gxt"
gxt -g III -r -i "III PC/russian.txt" -o "III PC/russian.gxt"