gxt -g LCS -i "LCS PS2/english.txt" -o "LCS PS2/english.gxt"
gxt -g LCS -i "LCS PS2/german.txt" -o "LCS PS2/german.gxt"
gxt -g LCS -i "LCS PS2/french.txt" -o "LCS PS2/french.gxt"
gxt -g LCS -i "LCS PS2/italian.txt" -o "LCS PS2/italian.gxt"
gxt -g LCS -i "LCS PS2/spanish.txt" -o "LCS PS2/spanish.gxt"
