gxt -g III -i "III Mobile/american.txt" -o "III Mobile/american.gxt"
gxt -g III -i "III Mobile/english.txt" -o "III Mobile/english.gxt"
gxt -g III -i "III Mobile/french.txt" -o "III Mobile/french.gxt"
gxt -g III -i "III Mobile/german.txt" -o "III Mobile/german.gxt"
gxt -g III -i "III Mobile/italian.txt" -o "III Mobile/italian.gxt"
gxt -g III -i "III Mobile/spanish.txt" -o "III Mobile/spanish.gxt"
gxt -g III -k -m -i "III Mobile/korean.txt" -o "III Mobile/korean.gxt"
gxt -g III -j -m -i "III Mobile/japanese.txt" -o "III Mobile/japanese.gxt"