gxt -g SA -i "SA PC/american.txt" "SA PC/americanDialogue.txt" "SA PC/americanMission.txt" "SA PC/americanPC.txt" -o "SA PC/american.gxt"
gxt -g SA -i "SA PC/french.txt" "SA PC/frenchDialogue.txt" "SA PC/frenchMission.txt" "SA PC/frenchPC.txt" -o "SA PC/french.gxt"
gxt -g SA -i "SA PC/german.txt" "SA PC/germanDialogue.txt" "SA PC/germanMission.txt" "SA PC/germanPC.txt" -o "SA PC/german.gxt"
gxt -g SA -i "SA PC/italian.txt" "SA PC/italianDialogue.txt" "SA PC/italianMission.txt" "SA PC/italianPC.txt" -o "SA PC/italian.gxt"
gxt -g SA -i "SA PC/spanish.txt" "SA PC/spanishDialogue.txt" "SA PC/spanishMission.txt" "SA PC/spanishPC.txt" -o "SA PC/spanish.gxt"