gxt -i "VC PS2/american.txt" -o "VC PS2/american.gxt" -t "tables/vc_sa_table.txt"
gxt -i "VC PS2/french.txt" -o "VC PS2/french.gxt" -t "tables/vc_sa_table.txt"
gxt -i "VC PS2/german.txt" -o "VC PS2/german.gxt" -t "tables/vc_sa_table.txt"
gxt -i "VC PS2/italian.txt" -o "VC PS2/italian.gxt" -t "tables/vc_sa_table.txt"
gxt -i "VC PS2/spanish.txt" -o "VC PS2/spanish.gxt" -t "tables/vc_sa_table.txt"