gxt -g VCS -i "VCS PS2/english.txt" -o "VCS PS2/english.gxt"
gxt -g VCS -i "VCS PS2/german.txt" -o "VCS PS2/german.gxt"
gxt -g VCS -i "VCS PS2/french.txt" -o "VCS PS2/french.gxt"
gxt -g VCS -i "VCS PS2/italian.txt" -o "VCS PS2/italian.gxt"
gxt -g VCS -i "VCS PS2/spanish.txt" -o "VCS PS2/spanish.gxt"
