gxt -g VC -m -i "VC Mobile/american.txt" -o "VC Mobile/american.gxt"
gxt -g VC -m -i "VC Mobile/french.txt" -o "VC Mobile/french.gxt"
gxt -g VC -m -i "VC Mobile/german.txt" -o "VC Mobile/german.gxt"
gxt -g VC -m -i "VC Mobile/italian.txt" -o "VC Mobile/italian.gxt"
gxt -g VC -m -i "VC Mobile/spanish.txt" -o "VC Mobile/spanish.gxt"
gxt -g VC -m -k -i "VC Mobile/korean.txt" -o "VC Mobile/korean.gxt"
gxt -g VC -m -j -i "VC Mobile/japanese.txt" -o "VC Mobile/japanese.gxt"