gxt -g VC -i "VC PS2/american.txt" -o "VC PS2/american.gxt"
gxt -g VC -i "VC PS2/french.txt" -o "VC PS2/french.gxt"
gxt -g VC -i "VC PS2/german.txt" -o "VC PS2/german.gxt"
gxt -g VC -i "VC PS2/italian.txt" -o "VC PS2/italian.gxt"
gxt -g VC -i "VC PS2/spanish.txt" -o "VC PS2/spanish.gxt"